### ISSUE TITLE
Error while playing, maybe enter the 1st scene.

### ISSUE THREAD

**Issue by spkingr** [ja-brouil/TBS_GoDot#2]
I cloned your project and the game started then crash for the reason:

> Invalid type in function 'add_child' in base 'Node2D (Eirika.gd)'. The Object-derived class of argument 1 (Reference (Unit_Stats.gd)) is not a subclass of the expected argument class.

And I found that your script `Unit_Stats.gd` is not `extends Node2D`, I add the line, then another problem occurred, the `name` property is accidentally overridden, so I replaced all your `name` to 'xname', `UnitStats.name` to `UnitStats.xname` and now the game plays well.

**Comment by spkingr** [comment]
BTY, I saw your repository in comments in Reddit, but I lost the post url.

**Comment by ja-brouil** [comment]
Heya!

I have actually fixed these issues today. The game needs to be running in the lastest version of Godot 3.1.2 and not 3.1.1 because of some inside three bug.

I will push a new commit later today.

**Comment by ja-brouil** [comment]
I just pushed an update to fix this issue. Please update and it should be good to go.
